#应用配置
spring:
  application:
    name: dynamic-datasource-springboot
server:
  port: 80
#日志配置
logging:
  path: logs
  config: classpath:logback-spring.xml
  level:
    com:
      comven:
        example:
          mapper: info
#主数据源配置
hikari:
  master:
    jdbc-url: jdbc:mysql://127.0.0.1:3306/db?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password:
    maximum-pool-size: 10
    pool-name: master
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1765000
    data-source-properties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
      useLocalSessionState: true
      useLocalTransactionState: true
      rewriteBatchedStatements: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      elideSetAutoCommits: true
      maintainTimeStats: false
  #从数据源1配置
  slave1:
    jdbc-url: jdbc:mysql://127.0.0.1:3316/db?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password:
    maximum-pool-size: 10
    pool-name: slave1
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1765000
    read-only: true
  slave2:
    jdbc-url: jdbc:mysql://127.0.0.1:3326/db?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password:
    maximum-pool-size: 10
    pool-name: slave2
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1765000
    read-only: true
#从数据库路由规则配置
slave:
  hosts: slave1,slave2
#mybatis配置
mybatis:
  type-aliases-package: com.wwh.pojo
  mapper-locations: classpath:/META-INF/mybatis/mapper/*.xml
